/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Yha
 */
import java.sql.*;
import java.awt.*;
import java.util.*;
import javax.swing.*;
public class main extends javax.swing.JFrame {
    static ArrayList<akun> dataAkun = new ArrayList<>();
    boolean kondisi;

    
    static void readDB(){
        dataAkun.clear();
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/dbtv", "root", "");
            Statement stmt = conn.createStatement();
            ResultSet rs = stmt.executeQuery("Select * from akun");
            if(!rs.next()){
                System.out.println("No Data Yet");
            }else{
                do{
                    String nama = rs.getString("nama");
                    String mail = rs.getString("email");
                    String status = rs.getString("status");
                    String pass = rs.getString("password");
                    String alamat = rs.getString("alamat");
                    int id = rs.getInt("id");
                    akun newData = new akun(nama, mail, alamat, pass, status, id);
                    dataAkun.add(newData);
                }while(rs.next());
            }
            rs.close();
            stmt.close();
            conn.close();
        }catch(Exception e){
            e.printStackTrace();
        }
    }
    
    
    
    CardLayout clays;
    public main() {
        initComponents();
        clays = (CardLayout)(CardPanel.getLayout());
        readDB();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    void cekRegis(){
        kondisi = true;
        if(txtNamaReg.getText().isEmpty()){
            kondisi = false;
        }else if(txtAlamatReg.getText().isEmpty()){
            kondisi = false;
        }else if(txtEmailReg.getText().isEmpty()){
            kondisi = false;
        }else if(txtPassReg.getText().isEmpty()){
            kondisi = false;
        }
    }
    void cekLogin(){
        kondisi = true;
        if(txtEmail.getText().isEmpty()){
            kondisi = false;
        }else if(txtPass.getText().isEmpty()){
            kondisi = false;
        }
    }
    void bersih(){
        txtEmail.setText("");
        txtPass.setText("");
        txtNamaReg.setText("");
        txtEmailReg.setText("");
        txtAlamatReg.setText("");
        txtPassReg.setText("");
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        btnExit2 = new javax.swing.JLabel();
        CardPanel = new javax.swing.JPanel();
        LoginPanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        btnMasuk = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtPass = new javax.swing.JPasswordField();
        labelDaftar = new javax.swing.JLabel();
        RegisPanel = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        labelLogin = new javax.swing.JLabel();
        btnDaftar = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        txtEmailReg = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtNamaReg = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtAlamatReg = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtPassReg = new javax.swing.JPasswordField();
        jLabel18 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        btnExit2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        btnExit2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnExit2.setText("X");
        btnExit2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExit2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExit2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(603, Short.MAX_VALUE)
                .addComponent(btnExit2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnExit2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, -1));

        CardPanel.setLayout(new java.awt.CardLayout());

        LoginPanel.setBackground(new java.awt.Color(255, 255, 255));
        LoginPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        jLabel5.setText("Password");
        LoginPanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 90, 20));

        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });
        LoginPanel.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 390, 40));

        jLabel8.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        jLabel8.setText("E-Mail");
        LoginPanel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 90, 20));

        btnMasuk.setBackground(new java.awt.Color(255, 51, 51));
        btnMasuk.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMasuk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMasukMouseClicked(evt);
            }
        });

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("MASUK");

        javax.swing.GroupLayout btnMasukLayout = new javax.swing.GroupLayout(btnMasuk);
        btnMasuk.setLayout(btnMasukLayout);
        btnMasukLayout.setHorizontalGroup(
            btnMasukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnMasukLayout.createSequentialGroup()
                .addContainerGap(157, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(155, 155, 155))
        );
        btnMasukLayout.setVerticalGroup(
            btnMasukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        LoginPanel.add(btnMasuk, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, 390, 40));

        jLabel10.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel10.setText("SIGN IN.");
        LoginPanel.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 90, 40));
        LoginPanel.add(txtPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 390, 40));

        labelDaftar.setBackground(new java.awt.Color(255, 255, 255));
        labelDaftar.setForeground(new java.awt.Color(51, 51, 255));
        labelDaftar.setText("Registrasi");
        labelDaftar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelDaftar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelDaftarMouseClicked(evt);
            }
        });
        LoginPanel.add(labelDaftar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 280, -1, -1));

        CardPanel.add(LoginPanel, "card2");

        RegisPanel.setBackground(new java.awt.Color(255, 255, 255));
        RegisPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel11.setText("SIGN UP.");
        RegisPanel.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 90, 40));

        labelLogin.setBackground(new java.awt.Color(255, 255, 255));
        labelLogin.setForeground(new java.awt.Color(51, 51, 255));
        labelLogin.setText("Log In");
        labelLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelLoginMouseClicked(evt);
            }
        });
        RegisPanel.add(labelLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 290, -1, -1));

        btnDaftar.setBackground(new java.awt.Color(255, 51, 51));
        btnDaftar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDaftar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDaftarMouseClicked(evt);
            }
        });

        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("DAFTAR");

        javax.swing.GroupLayout btnDaftarLayout = new javax.swing.GroupLayout(btnDaftar);
        btnDaftar.setLayout(btnDaftarLayout);
        btnDaftarLayout.setHorizontalGroup(
            btnDaftarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnDaftarLayout.createSequentialGroup()
                .addGap(156, 156, 156)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(156, Short.MAX_VALUE))
        );
        btnDaftarLayout.setVerticalGroup(
            btnDaftarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnDaftarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        RegisPanel.add(btnDaftar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, 390, 40));

        txtEmailReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailRegActionPerformed(evt);
            }
        });
        RegisPanel.add(txtEmailReg, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 80, 230, 40));

        jLabel15.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        jLabel15.setText("E-Mail");
        RegisPanel.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 50, 90, 20));

        txtNamaReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaRegActionPerformed(evt);
            }
        });
        RegisPanel.add(txtNamaReg, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 230, 40));

        jLabel16.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        jLabel16.setText("Nama");
        RegisPanel.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 90, 20));

        txtAlamatReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAlamatRegActionPerformed(evt);
            }
        });
        RegisPanel.add(txtAlamatReg, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 230, 40));

        jLabel17.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        jLabel17.setText("Alamat");
        RegisPanel.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 90, 20));
        RegisPanel.add(txtPassReg, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 160, 230, 40));

        jLabel18.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        jLabel18.setText("Password");
        RegisPanel.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 130, -1, 20));

        CardPanel.add(RegisPanel, "card3");

        getContentPane().add(CardPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 650, 330));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void btnExit2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExit2MouseClicked
        this.dispose();
    }//GEN-LAST:event_btnExit2MouseClicked

    private void btnMasukMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMasukMouseClicked
        boolean salah = false;
        cekLogin();
        if(kondisi){
            for(akun cek : dataAkun){
                if(cek.getEmail().equals(txtEmail.getText()) && cek.getPassword().equals(txtPass.getText())){
                    this.dispose();
                    JOptionPane.showMessageDialog(null , "Login Sebagai " + cek.getStatus());
                    if(cek.getStatus().equals("USER")){
                        System.out.println("user");
                    }else if(cek.getStatus().equals("ADMIN")){
                        AdminFrame am = new AdminFrame();
                        am.setVisible(true);
                    }
                    salah = true;
                    break;
                }
            }
            if(!salah){
                JOptionPane.showMessageDialog(null , "E-mail Atau Password Salah");
            }   
            
        }else{
            JOptionPane.showMessageDialog(null , "DATA BELUM LENGKAP");
        }
        
    }//GEN-LAST:event_btnMasukMouseClicked

    private void btnDaftarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDaftarMouseClicked
        boolean ada = false;
        cekRegis();
        if(kondisi){
            for(akun cekData : dataAkun){
                if(cekData.getEmail().equals(txtEmailReg.getText())){
                    ada = true;
                    JOptionPane.showMessageDialog(null , "E-mail Sudah Terdaftar");
                }
            }
            if(!ada){
                String nama, alamat, email, password;
                nama = txtNamaReg.getText();
                alamat = txtAlamatReg.getText();
                email = txtEmailReg.getText();
                password = txtPassReg.getText();
                try{
                    Class.forName("com.mysql.cj.jdbc.Driver");
                    Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/dbtv", "root", "");
                    Statement stmt = conn.createStatement();
                    stmt.executeUpdate("insert into akun(id, nama, email, alamat, password, status) values(0, '"+nama+"', '"+email+"', '"+alamat+"', '"+password+"', 'USER')");
                    stmt.close();
                    conn.close();
                }catch(Exception e){
                    e.printStackTrace();
                }
                JOptionPane.showMessageDialog(null , "Data Berhasil Ditambahkan");
                clays.next(CardPanel);
                bersih();
            }
            readDB();
        }else{
            JOptionPane.showMessageDialog(null , "Data Belum Lengkap");
        }
    }//GEN-LAST:event_btnDaftarMouseClicked

    private void txtEmailRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailRegActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailRegActionPerformed

    private void txtNamaRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaRegActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaRegActionPerformed

    private void txtAlamatRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAlamatRegActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAlamatRegActionPerformed

    private void labelLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelLoginMouseClicked
        clays.next(CardPanel);
    }//GEN-LAST:event_labelLoginMouseClicked

    private void labelDaftarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelDaftarMouseClicked
        clays.next(CardPanel);
    }//GEN-LAST:event_labelDaftarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CardPanel;
    private javax.swing.JPanel LoginPanel;
    private javax.swing.JPanel RegisPanel;
    private javax.swing.JPanel btnDaftar;
    private javax.swing.JLabel btnExit2;
    private javax.swing.JPanel btnMasuk;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel labelDaftar;
    private javax.swing.JLabel labelLogin;
    private javax.swing.JTextField txtAlamatReg;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEmailReg;
    private javax.swing.JTextField txtNamaReg;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JPasswordField txtPassReg;
    // End of variables declaration//GEN-END:variables
}
